/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.Hora;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cmdGuardar.setEnabled(true);
        cmdComparar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdValidar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtHora1 = new javax.swing.JTextField();
        txtMinutos1 = new javax.swing.JTextField();
        txtSegundos1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtHoras2 = new javax.swing.JTextField();
        txtMinutos2 = new javax.swing.JTextField();
        txtSegundos2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmdGuardar = new javax.swing.JButton();
        cmdComparar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdValidar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Horas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 11, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora #1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHora1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHora1KeyTyped(evt);
            }
        });
        jPanel2.add(txtHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, -1));

        txtMinutos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinutos1KeyTyped(evt);
            }
        });
        jPanel2.add(txtMinutos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 60, -1));

        txtSegundos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundos1KeyTyped(evt);
            }
        });
        jPanel2.add(txtSegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 60, -1));

        jLabel2.setText("Horas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setText("Minutos");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel4.setText("Segundos");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel5.setText(":");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 20, 20));

        jLabel6.setText(":");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 20, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 310, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora #2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHoras2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoras2KeyTyped(evt);
            }
        });
        jPanel3.add(txtHoras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, -1));

        txtMinutos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinutos2KeyTyped(evt);
            }
        });
        jPanel3.add(txtMinutos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 60, -1));

        txtSegundos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundos2KeyTyped(evt);
            }
        });
        jPanel3.add(txtSegundos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 70, -1));

        jLabel7.setText("Horas");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel8.setText("Minutos");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel9.setText("Segundos");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel10.setText(":");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 10, 20));

        jLabel11.setText(":");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 10, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 300, 130));

        cmdGuardar.setText("GUARDAR");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        cmdComparar.setText("COMPARAR");
        cmdComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCompararActionPerformed(evt);
            }
        });
        jPanel1.add(cmdComparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        cmdMostrar.setText("MOSTRAR");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        cmdValidar.setText("VALIDAR");
        cmdValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdValidarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        cmdLimpiar.setText("LIMPIAR");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
    int hora1, min1, seg1, hora2, min2, seg2;
        if (txtHora1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Hora 1", "error", JOptionPane.ERROR_MESSAGE);
            txtHora1.requestFocusInWindow();
        } else if (txtMinutos1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Minutos de la hora 1", "error", JOptionPane.ERROR_MESSAGE);
            txtMinutos1.requestFocusInWindow();
        } else if (txtSegundos1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Segundos de la hora 1", "error", JOptionPane.ERROR_MESSAGE);
            txtSegundos1.requestFocusInWindow();
        } else if (txtHoras2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Hora 2", "error", JOptionPane.ERROR_MESSAGE);
            txtHoras2.requestFocusInWindow();
        } else if (txtMinutos2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Minutos de la hora 2", "error", JOptionPane.ERROR_MESSAGE);
            txtMinutos2.requestFocusInWindow();
        } else if (txtSegundos2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Segundos de la hora 2", "error", JOptionPane.ERROR_MESSAGE);
            txtSegundos2.requestFocusInWindow();
        } else {
            hora1 = Integer.parseInt(txtHora1.getText());
            min1 = Integer.parseInt(txtMinutos1.getText());
            seg1 = Integer.parseInt(txtSegundos1.getText());
            hora2 = Integer.parseInt(txtHoras2.getText());
            min2 = Integer.parseInt(txtMinutos2.getText());
            seg2 = Integer.parseInt(txtSegundos2.getText());
            Hora h = new Hora(hora1, min1, seg1);
            Hora h2 = new Hora(hora2, min2, seg2);
            cmdGuardar.setEnabled(false);
            cmdComparar.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdValidar.setEnabled(true);
            cmdLimpiar.setEnabled(true);
            txtHora1.setEditable(false);
            txtMinutos1.setEditable(false);
            txtSegundos1.setEditable(false);
            txtHoras2.setEditable(false);
            txtMinutos2.setEditable(false);
            txtSegundos2.setEditable(false);
            JOptionPane.showMessageDialog(this, "Horas guardadas correctamente");
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdValidarActionPerformed
    String H1, H2;
    H1 = h.validacion();
    JOptionPane.showMessageDialog(this, "La hora 1 " + H1);
    H2 = h2.validacion();
    JOptionPane.showMessageDialog(this, "La hora 2 " + H2);
    }//GEN-LAST:event_cmdValidarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
    cmdGuardar.setEnabled(true);
        cmdComparar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdValidar.setEnabled(false);
        cmdLimpiar.setEnabled(true);
        txtHora1.setEditable(true);
        txtMinutos1.setEditable(true);
        txtSegundos1.setEditable(true);
        txtHoras2.setEditable(true);
        txtMinutos2.setEditable(true);
        txtSegundos2.setEditable(true);
        txtHora1.setText("");
        txtMinutos1.setText("");
        txtSegundos1.setText("");
        txtHoras2.setText("");
        txtMinutos2.setText("");
        txtSegundos2.setText("");
        txtHora1.requestFocusInWindow();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCompararActionPerformed
    String c;
    c = h.comparacion(h2);
    JOptionPane.showMessageDialog(this, c);
    }//GEN-LAST:event_cmdCompararActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
    String aux1, aux2;
    aux1 = h.mostrar();
    aux2 = h2.mostrar();
    JOptionPane.showMessageDialog(this, "La hora 1 es: " + aux1);
    JOptionPane.showMessageDialog(this, "La hora 2 es: " + aux2);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void txtHora1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHora1KeyTyped
    char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
    getToolkit().beep();
    evt.consume();

    }
    }//GEN-LAST:event_txtHora1KeyTyped

    private void txtMinutos1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinutos1KeyTyped
    char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
    getToolkit().beep();
    evt.consume();

    }
    }//GEN-LAST:event_txtMinutos1KeyTyped

    private void txtSegundos1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundos1KeyTyped
     char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
    getToolkit().beep();
    evt.consume();

    }
    }//GEN-LAST:event_txtSegundos1KeyTyped

    private void txtHoras2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoras2KeyTyped
     char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
    getToolkit().beep();
    evt.consume();

    }
    }//GEN-LAST:event_txtHoras2KeyTyped

    private void txtMinutos2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinutos2KeyTyped
     char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
    getToolkit().beep();
    evt.consume();

    }
    }//GEN-LAST:event_txtMinutos2KeyTyped

    private void txtSegundos2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundos2KeyTyped
     char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
    getToolkit().beep();
    evt.consume();

    }
    }//GEN-LAST:event_txtSegundos2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdComparar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtHora1;
    private javax.swing.JTextField txtHoras2;
    private javax.swing.JTextField txtMinutos1;
    private javax.swing.JTextField txtMinutos2;
    private javax.swing.JTextField txtSegundos1;
    private javax.swing.JTextField txtSegundos2;
    // End of variables declaration//GEN-END:variables


}